## Question - 1:

#### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
# importing numpy with alias name
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question - 2

#### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
# importing numpy with alias name
import numpy as np

# creating a 2 empty list:
lst_1 = []
lst_2 = []

# getting values for lst_1 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_1 : "))
  lst_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_2 : "))
  lst_2.append(x)

# converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)





Enter the value for lst_1 : 1

Enter the value for lst_1 : 0

Enter the value for lst_1 : 9

Enter the value for lst_1 : 2

Enter the value for lst_1 : 8

Enter the value for lst_2 : 3

Enter the value for lst_2 : 4

Enter the value for lst_2 : 7

Enter the value for lst_2 : 6

Enter the value for lst_2 : 5

Array value for concatenated arr : [1 0 9 2 8 3 4 7 6 5]

Sorted Array for concatenated arr : [0 1 2 3 4 5 6 7 8 9]


## Question - 3:

#### Write a code snippet to find the dimensions of a ndarray and its size.

#### snippet for finding dimension:

ArrayName.ndim

#### snippet for finding size:

ArrayName.size


In [3]:
# importing numpy
import numpy as np

# creating a 2d array
arr = np.array([[1,2,3],[1,3,5]])

# Printing array dimensions (axes)
print("\nDimensions in array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)





Dimensions in array :  2

Size of array :  6


## Question - 4:

#### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
##### Hint: np.newaxis, np.expand_dims

### newaxis snippet:

ArrayName[numpy.newaxis, :] // row major

ArrayName[:, numpy.newaxis] // column major

In [7]:
# importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)



Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


### expand_dims snippet:

numpy.expand_dims(ArrayName, axis = 0) // row major

numpy.expand_dims(ArrayName, axis = 1) // column major

In [9]:
# importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(10)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


## Question - 5:

#### Consider two square numpy arrays. Stack them vertically and horizontally.

##### Hint: Use vstack(), hstack()

In [11]:
# importing numpy
import numpy as np

# creating a array with square values
arr_1 = np.array([1, 4, 9, 16, 25])
arr_2 = np.array([36, 49, 64, 81, 100])

# stacking and printing the value
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))




Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]

Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


## Question - 6:

##### How to get unique items and counts of unique items?

unique method in numpy is used to get the unique values from the list and return count attribute of unique method return the count of unique value from the list.

In [20]:
# importing numpy
import numpy as np

# creating a array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

# making a 
arr = np.asarray((unique, counts)).T

print(arr)


[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
